### ISSUE TITLE
Add API docs

### ISSUE THREAD

**Issue by lucaspouzac** [varnish/vagent2#111]
Hi, 

Could you add API docs ?

Thanks

**Comment by KristianLyng** [comment]
I would suggest a different route: add a Description argument to http_register() and make it available. A generic /help might work then.

The reason I am sceptical of an api document is that it has to be kept in sync, and the design goal of the agent is to be self documenting to avoid just such a problem and keep the release process simple.

**Comment by freshteapot** [comment]
For when the time comes, here is where the info can be found.

In mk_help, we get an overview of the api calls.
https://github.com/varnish/vagent2/blob/master/src/modules/vcl.c

**Comment by Dridi** [comment]
See #177, not planning to do more for now.

ETIMEDOUT
