### ISSUE TITLE
Timeline for varnish 4 agent? 

### ISSUE THREAD

**Issue by profMikeBroyles** [varnish/vagent2#118]
My apologies if this is the incorrect place to ask this.  Does anyone have a timeline (or any current development) for a varnish 4 agent?

**Comment by fgsch** [comment]
A Varnish 4 is in the repo.

**Comment by profMikeBroyles** [comment]
Excellent! Thank you

On Monday, February 16, 2015, Federico G. Schwindt <notifications@github.com>
wrote:

> Closed #118 <https://github.com/varnish/vagent2/issues/118>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/varnish/vagent2/issues/118#event-236499172>.
>


-- 
Sent from Gmail Mobile
