### ISSUE TITLE
agent crash on file with 0 bytes

### ISSUE THREAD

**Issue by adeelshahid** [varnish/vagent2#119]
create a file any file :dancer: foo.bar inside /html/ directory

access is using agent's rest interface /html/foo.bar

if foo.bar has 0 bytes, no content it will crash the agent.

from */var/log/syslog/*

Nov  7 13:34:14 cache1 varnish-agent[4553]: modules/html.c:89: html_reply: Assertion `ret>0' failed. Aborting.

**Desirable Behaviour**
Agent should return file with blank contents. If file is found but has no contents.

**Comment by brandonwamboldt** [comment]
FYI I also have this error (using the `3.0` branch)
