### ISSUE TITLE
n_arg_sock (modules/vadmin.c:134): Using -T argument from shmlog: 127.0.0.1 6082

### ISSUE THREAD

**Issue by sz00gun** [varnish/vagent2#132]
Hello,

after restarting varnish-agent2 and command varnish-agent -H /var/www/html/Varnish-Agent-Dashboard

I get this error:

service varnish-agent restart

[....] Restarting Varnish Agent: varnish-agentn_arg_sock (modules/vadmin.c:134): Using -T argument from shmlog: 127.0.0.1 6082
. ok

Got Varnish 3.0.6 and Varnish-Agent - the latest from Debian apt-get

How to fix it?
Please advise

**Comment by brandonwamboldt** [comment]
That's not actually an error. It's a normal notice message.

**Comment by brandonwamboldt** [comment]
Basically just means that the Varnish Agent is automatically detecting the correct value for the `-T` argument since you didn't manually specify one.

**Comment by sz00gun** [comment]
Thank you, but still have a problem with a Dashboard for vagent2.

I have: stat() not happy while visit: http://94.xx.2xx.105:6085/html/Varnish-Agent-Dashboard/

any idea how to fix it?

**Comment by brandonwamboldt** [comment]
That's the not so friendly error that means 404 page not found. You just want:

http://94.xx.2xx.105:6085/html/

Since you started the dashboard with `-H /var/www/html/Varnish-Agent-Dashboard`, that should work.

**Comment by sz00gun** [comment]
Thanks Brandon,

after: varnish-agent -H /var/www/html/Varnish-Agent-Dashboard
I see SSH respond: n_arg_sock (modules/vadmin.c:134): Using -T argument from shmlog: 127.0.0.1 6082

while http://94.xx.2xx.105:6085/html/  I can see http://awesomescreenshot.com/00e4mjkqb3  which is OK, but I still cannot see the Dashboard ;(

Please advise

**Comment by brandonwamboldt** [comment]
That's the default "dashboard" that ships with Varnish Agent. It's possible you didn't kill the old process first.

Run:

```
ps -ef | grep varnish-agent
```

Look for all running `varnish-agent` processes and kill them:

```
sudo killall varnish-agent
```

or kill them one at a time with `kill <PID>`. Then start your varnish dashboard again and it should work.

**Comment by sz00gun** [comment]
Master! Thank you, this helped me, 

the last problem is this anoying message eg. after varnish-agent restart::

 service varnish-agent restart
[....] Restarting Varnish Agent: varnish-agentn_arg_sock (modules/vadmin.c:134): Using -T argument from command line: localhost:6082
. ok

How to get rid of this message: varnish-agentn_arg_sock (modules/vadmin.c:134): Using -T 

I added this: 
DAEMON_OPTS="-K /etc/varnish/agent_secret \
		     -T localhost:6082"

to: /etc/default/varnish-agent

but this message still there...

Please advise

**Comment by fgsch** [comment]
Please see the comment 2 from @brandonwamboldt:

> That's not actually an error. It's a normal notice message.
