### ISSUE TITLE
VarnishAgent starts every reboot of server?

### ISSUE THREAD

**Issue by sz00gun** [varnish/vagent2#135]
Is possible VarnishAgent starts itself every time server is rebooting?

It is not point start SSH with: varnish-agent -H /var/www/html/varnish-dashboard

Please advise

**Comment by sz00gun** [comment]
Please help me with this...

**Comment by fgsch** [comment]
Yes, it's possible. 

Are you comping from sources? What platform are you using?

**Comment by sz00gun** [comment]
Hi,

yes, vagent2 from the source. I use: Debian 7 64bits, Varnish 3.0.7 64 bit.

**Comment by fgsch** [comment]
Run `update-rc.d varnish-agent defaults` to make sure it starts on reboot.

**Comment by sz00gun** [comment]
well... an error there:

**Comment by fgsch** [comment]
Are you the same person that in #132 wrote it ran:

service varnish-agent restart

If so, the init script should be there.

**Comment by fgsch** [comment]
Unless you use the package the necessary bits and pieces won't be installed from sources.
You will need to copy the init script (debian/init) to /etc/init.d/varnish-agent and then run update-rc.d.
Other things might be missing. I'd suggest you to use the pre-built packages instead however.
