### ISSUE TITLE
varnish-agent: varnish is not a valid user

### ISSUE THREAD

**Issue by thiagolocatelli** [varnish/vagent2#137]
I keep getting this error message but I cant figure it out what is wrong. I am not running as varnish user and neither my secret file has a varnish user.
Any ideas?

sudo LD_LIBRARY_PATH=/home/thiago/varnish/agent2/lib/ ./bin/varnish-agent -K agent_secret -H varnish-dashboard-master/ -T localhost:6082 -S /home/thiago/varnish/etc/varnish/secret -n /home/thiago/varnish/workspace -d

**Comment by fgsch** [comment]
If you are not running as the default user you need to use -u.

Run the agent with -h for the help.
