### ISSUE TITLE
Unable to login to varnish agent UI

### ISSUE THREAD

**Issue by linuxbsdfreak** [varnish/vagent2#139]
Hi,

I am trying to connect to http://ipaddress:6085/html/

It only displays 

Authorize, please.

If Varnish Agent was installed from packages, the /etc/varnish/agent_secret file contains generated credentials.

I have generated a base64 password and providing the correct credentials

I am using the dashboard from: https://github.com/brandonwamboldt/varnish-dashboard

Could you help me debug what could be the problem ?

Regards,
Kevin

**Comment by linuxbsdfreak** [comment]
Issue is fixed. Tested and its working.

**Comment by Dridi** [comment]
@izghitu the `/etc/varnish/agent_secret` file should contain your credentials in the form of `$login:$password` to be used when prompt with a 401 response.
