### ISSUE TITLE
vagent error,please help me

### ISSUE THREAD

**Issue by Yanxiangxiang** [varnish/vagent2#140]
command:
/data/vagent2/bin/varnish-agent -T 127.0.0.1:8001 -H /data/varnish-dashboard-master/ -n /data/varnish -K /etc/varnish/agent_secret -z http://ip:port

output:
n_arg_sock (modules/vadmin.c:91): Couldn't open VSM: Not a VSM file /data/varnish/_.vsm

n_arg_sock (modules/vadmin.c:117): No shmlog and no -S arg. Unknown if authentication will work.

Anyone knows?Please explain this.

**Comment by fgsch** [comment]
How are you starting / running varnishd and what's the output of ls -l /data/varnish?

For some reason the agent is not able to find the Varnish shmlog in /data/varnish.

**Comment by Yanxiangxiang** [comment]
start varnishd:
/data/varnish/sbin/varnishd -f /data/varnish/etc/varnish/default.vcl -n /data/varnish/ -s malloc,2G -T 127.0.0.1:8001 -a 0.0.0.0:80 

ls /data/varnish/:
bin  etc  include  lib  logs sbin  share var vcl.iZnPNxIb.so  _.vsm

**Comment by fgsch** [comment]
You forgot the -l in ls. I suspect your _.vsm is not readable by varnishd.

Are you starting varnishd from command line or using the init scripts?

**Comment by Yanxiangxiang** [comment]
Yes,I start varnishd from command line,my boss said I forgot "varnishd ...-S ...secret",and -n /data/varnish/logs.It must be logs dir.
And,varnishncsa -n /data/varnish/logs -c -f -a -w /data/varnish/logs/varnish.log.
I'm trying...

**Comment by fgsch** [comment]
First I'd suggest you to use the init scripts to avoid any issues like missing settings, etc.

From what you shown above /data/varnish/ is OK (_.vsm is in there) but permissions are probably wrong.

**Comment by Yanxiangxiang** [comment]
Oh,whatever,thanks for help.
