### ISSUE TITLE
no member named 'fmt' in 'struct VSC_desc'

### ISSUE THREAD

**Issue by tommy20061222** [varnish/vagent2#141]
Hey,
 I got following errors when i do the make.

modules/vstat.c:76:27: error: no member named 'fmt' in 'struct VSC_desc'
        assert(!strcmp(pt->desc->fmt, "uint64_t"));
                       ~~~~~~~~  ^
../include/common.h:125:6: note: expanded from macro 'assert'
        ((expr) ? (void)(0) : assert_fail(#expr, __FILE__, __LINE__, __func__));
          ^
modules/vstat.c:94:54: error: no member named 'flag' in 'struct VSC_desc'
        VSB_printf(out_vsb, "\"flag\": \"%c\", ", pt->desc->flag);
                                                  ~~~~~~~~  ^
Thank you

**Comment by daghf** [comment]
Hi.

Which branch of vagent2 is this, and which version of Varnish Cache are you building against?

**Comment by tommy20061222** [comment]
Hi,
  Thank you!  I use varnish 4.0.0, installed from source. The branch i use for vagent is master. Thank you again

**Comment by tommy20061222** [comment]
any updates?

**Comment by daghf** [comment]
Hi,

I tested branch 4.0 against Varnish Cache git tag 4.0.0, and that builds just fine. Can you confirm that this is the Varnish version your are building against? (varnishd -V)

Could you also please attach your config.log file?

**Comment by tommy20061222** [comment]
varnishd -V
      varnishd (varnish-trunk revision 3ba970e)
      Copyright (c) 2006 Verdens Gang AS
      Copyright (c) 2006-2015 Varnish Software AS

Followings errors are from right after i execute 'make'

gcc -DHAVE_CONFIG_H -I. -I..  -I../include  -I/usr/local/include/varnish  -g -Wall -Werror -Wstrict-prototypes -Wmissing-prototypes -Wpointer-arith -Wreturn-type -Wwrite-strings -Wswitch -Wshadow -Wcast-align -Wunused-parameter -Wchar-subscripts -Winline -Wnested-externs -Wredundant-decls -Wformat -Wextra -Wno-missing-field-initializers -Wno-sign-compare -fstack-protector-all -DAGENT_PERSIST_DIR='"/usr/local/var/varnish-agent"' -DAGENT_HTML_DIR='"/usr/local/share/varnish-agent/html"' -I/usr/local/Cellar/libmicrohttpd/0.9.42/include   -g -O2 -MT modules/varnish_agent-vstat.o -MD -MP -MF modules/.deps/varnish_agent-vstat.Tpo -c -o modules/varnish_agent-vstat.o `test -f 'modules/vstat.c' || echo './'`modules/vstat.c
modules/vstat.c:75:27: error: no member named 'fmt' in 'struct VSC_desc'
        assert(!strcmp(pt->desc->fmt, "uint64_t"));
                       ~~~~~~~~  ^
../include/common.h:125:6: note: expanded from macro 'assert'
        ((expr) ? (void)(0) : assert_fail(#expr, __FILE__, __LINE__, __func__));
          ^
modules/vstat.c:93:54: error: no member named 'flag' in 'struct VSC_desc'
        VSB_printf(out_vsb, "\"flag\": \"%c\", ", pt->desc->flag);
                                                  ~~~~~~~~  ^
2 errors generated.
make[2]: *** [modules/varnish_agent-vstat.o] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2

Thank you again

**Comment by fgsch** [comment]
@tommy20061222 You are using varnish-master, not 4.0.0 as you stated in your comment.
Is this what you intended?

**Comment by tommy20061222** [comment]
yah, my bad. I download the varnish cache 4.0 and try to install from source. I did configure, make, make install. everything seems fine. But when i try to run varnish, i got following error

ld: can't open output file for writing './vcl.Qpob7HGr.so.ld_lW0QfS', errno=13 for architecture x86_64
clang: error: unable to remove file: Permission denied
clang: error: linker command failed with exit code 1 (use -v to see invocation)


So it is permission related, do you you which folder it tries to write into? maybe the question is when c compiler compile the vcl file, which folder it tries to write into?

Thank you

**Comment by tommy20061222** [comment]
i figure out to which directory it tries to write, at least on Mac. Here is the directory cd/usr/local/var/varnish/

Thank you all for the help

**Comment by tommy20061222** [comment]
I will close this thread. Thank you all again!
