### ISSUE TITLE
paramjson broken (asserts)

### ISSUE THREAD

**Issue by KristianLyng** [varnish/vagent2#143]
Sep 21 09:14:05 leia varnish-agent[11129]: modules/vparams.c:192: vparams_show_json: Assertion `term' failed. Aborting.

This is actually demonstrated by running make check - ./json.sh will fail.

However, this can be a bit hard to debug because the terminal is essentially overflowed with garbage when running the tests, so it's natural to assume that it's a problem with the test cases themself, but in this case it's not.

The guilty bit of code:

```
191                         term = strstr(raw+pos, "Default is: ");
192                         assert(term);
193                         pos = term-raw + strlen("Default is: ");
```

This never hits, because it's looking for "Default is: " in a bit of text that doesn't use that construct.

Reading mgt_param.c in varnishd trunk/master reveals:

```
277                         if (pp->def != NULL && strcmp(pp->def, VSB_data(vsb)))
278                                 VCLI_Out(cli, "%-*sDefault is: %s\n",
279                                     margin1, "", pp->def);
280                         if (pp->min != NULL)
281                                 VCLI_Out(cli, "%-*sMinimum is: %s\n",
282                                     margin1, "", pp->min);
283                         if (pp->max != NULL)
284                                 VCLI_Out(cli, "%-*sMaximum is: %s\n",
285                                     margin1, "", pp->max);
```

So obviously we can't assume that "Default is:", "Minimum is:" or "Maximum is:" is ever present in newer versions of varnishd.

**Comment by fgsch** [comment]
Right, that's why I documented the output in a789323f83cd432d81a8a11da45991ac8f811838.
It's in my plans to rewrite the whole thing so it works with V3 and V4.

**Comment by KristianLyng** [comment]
And that documentation does not match what the implementation actually does. The comment suggests that "Default is:" is optional (suggested by brackets), which is clearly not the case. Right now, this is a big issue for varnish 4.1 since the agent will just die if you try to review parameters in json.

I'm doing a param.show -j now, to avoid this whole thing (something that should've been done years ago), so it might be better to just fix it right now and instead rely on -j for future versions - as was always the plan. Ideally the agent shouldn't do ANY conversion between arbitrary ascii formating and json, but we're not quite there yet :)

**Comment by KristianLyng** [comment]
Basically this needs a short-term fix, and the long-term fix is to move the whole json bit into varnish.

**Comment by fgsch** [comment]
The documentation is for what Varnish does, not the agent, in order to rewrite this.
Since 4.1 is not out I don't think we need a short-term fix badly just yet. YMMV.

**Comment by KristianLyng** [comment]
d813ee3e17bd3d585a97b3d0e4f65a0372936edd fixes this. It attempts to add v4.0 compatibility but that's currently somewhat incomplete. I'll do some tweaks there, though.
