### ISSUE TITLE
Consider using varnishtest for the test suite

### ISSUE THREAD

**Issue by Dridi** [varnish/vagent2#156]
Hi there,

I just wanted to start discussions on the test suite now that we have an agent for Varnish 4.1. The latter basically allows to run arbitrary processes in the background and I think it's a good match for CLI and VSM consumers.

The VAC may also be emulated with a simple varnishtest `server`, but I'm not sure about this one...

Below is a partial rewrite of ban.sh vtc:

``` perl
server s1 {
    rxreq
    expect req.url == "/meh"
} -start

varnish v1 -vcl+backend "" -start

process p0 "inotifywait -e create ${tmpdir}/p1/agent.pid" -start

process p1 {
    set -e
    echo username:password >${tmpdir}/p1/secret
    varnish-agent -d -v \
        -p ${tmpdir}/p1 \
        -P ${tmpdir}/p1/agent.pid \
        -K ${tmpdir}/p1/secret \
        -n ${v1_name} \
        -c 6085
} -start

# Currently racy for the agent
process p0 -wait

# Ideally we should be able to wait for a file creation when
# the agent is ready and can be accessed through the API.
delay 1

client c1 {
    txreq -url "/meh"
    rxresp
} -run

# We don't want to put the auth header every time, it can
# be solved with a macro.
client c2 -connect localhost:6085 {
    txreq -url "/ban" \
        -hdr "Authorization: Basic dXNlcm5hbWU6cGFzc3dvcmQ="
    rxresp
    expect req.body !~ "/meh"

    txreq -req POST \
        -url "/ban" \
        -hdr "Authorization: Basic dXNlcm5hbWU6cGFzc3dvcmQ=" \
        -body "req.url ~ /meh"
    rxresp
    expect resp.status == 200

    txreq -url "/ban" \
        -hdr "Authorization: Basic dXNlcm5hbWU6cGFzc3dvcmQ="
    rxresp
    expect resp.body ~ "/meh"
} -run

shell "kill $(cat ${tmpdir}/p1/agent.pid)"
```

It is a lot more verbose, but hopefully also a lot more expressive. It's not that I don't like the current test suite, I myself rely on shell for testing quite often but in this case I believe we could make it more useful.

There are however pain points that need to be addressed:
- [ ] binding a random port
- [ ] the auth token
- [ ] waiting for the agent to be ready
- [ ] dealing with JSON payloads

For the random port, it's currently unsafe in the test shell suite, and varnishtest makes it even more complicated. I have a plan to solve that, BUT it needs to be done in varnishtest itself. I don't think I can get it done fast enough for 4.0.2.

For the auth token, I think it's rather trivial, I'm all for defining two macros for the plain text and base64 representations of the agent secret in the makefile. The hardest part would be naming the macros.

I think that areas where the varnishtest `client` is too limited can be solved with the varnishtest `shell` command that basically allows us to do anything. I'd in this case use `curl` and `jsonlint` and ditch `lwp-request`.

To run this test you need to add the varnish 4.1 binaries and `$(builddir)/src` to the PATH (again, trivial).

Thoughts?

**Comment by fgsch** [comment]
Saw the testing branch?

**Comment by Dridi** [comment]
I'm pretty sure you showed it to me at some point, and I forgot :)

**Comment by Dridi** [comment]
One more reason to ditch the current test suite, it leaks processes:

> WARNING: Process ID 2121 still running in chroot. Killing...

**Comment by Dridi** [comment]
ETIMEDOUT
