### ISSUE TITLE
Extra "," in the json file in vbackends module

### ISSUE THREAD

**Issue by aondio** [varnish/vagent2#157]
There is a "," after the last item in the json file. this breaks every possible json parser.
`
          "ref": "1",
                "admin": "probe",
                "probe": "     Healthy (no probe)"
       },
`

**Comment by aondio** [comment]
That's the resulting json from a test I've run.


{
 "backends" : [
	{
		"name": "default(127.0.0.1,,8080)",
		"ref": "1",
		"admin": "probe",
		"probe": "     Healthy (no probe)"
	},
	{
		"name": "s1(127.0.0.1,,8080)",
		"ref": "1",
		"admin": "probe",
		"probe": "     Healthy (no probe)"
	},
	{
		"name": "s2(127.0.0.1,,8080)",
		"ref": "1",
		"admin": "probe",
		"probe": "     Healthy (no probe)"
	},
	{
		"name": "s3(127.0.0.1,,8080)",
		"ref": "1",
		"admin": "probe",
		"probe": "     Healthy (no probe)"
	}
]
}

Asking to the reporter for more details.

**Comment by aondio** [comment]
Tried to reproduce, but with no success.
Waiting for more details to come.

**Comment by pedia** [comment]
#161 
we fixed it ugly.

**Comment by hugocruz** [comment]
The #161 fix works in some cases, but breaks in others. This is why for now is removed. We will look into adding it again after 4.1 hits the repo.
