### ISSUE TITLE
modules/vparams.c:171: vparams_show_json: Assertion `term' failed. Aborting.

### ISSUE THREAD

**Issue by rdetwiler** [varnish/vagent2#158]
Hello,
Getting the following after starting up the agent. This only happens once I view the web front end, then varnish-agent immediately crashes. This is on a Cent 7 box.

[root@lamp01 tests]# varnish-agent -d -v -z http://192.168.0.100:6085
n_arg_sock (modules/vadmin.c:134): -T argument computed to: 127.0.0.1 6082
main (main.c:332): Plugins initialized. -d argument given, so not forking.
LOGGER: http_run (modules/http.c:434): HTTP starting on port 6085
LOGGER: send_curl (modules/vac_register.c:78): Sending VAC registration request: http://67.219.146.19:6085
LOGGER: issue_curl (modules/curl.c:107): Issuing curl command with url=http://67.219.146.19:6085. Request body present
LOGGER: log_request (modules/http.c:300): PUT /
LOGGER: log_request (modules/http.c:300): PUT /
LOGGER: vac_register (modules/vac_register.c:123): VAC registration response: status=200 answer=OK
LOGGER: log_request (modules/http.c:300): GET /stats
LOGGER: log_request (modules/http.c:300): GET /stats
LOGGER: log_request (modules/http.c:300): GET /stats
LOGGER: log_request (modules/http.c:300): GET /stats
LOGGER: log_request (modules/http.c:300): GET /stats
LOGGER: log_request (modules/http.c:300): GET /vcljson/
LOGGER: vadmin_run (modules/vadmin.c:246): Running 'vcl.list'
LOGGER: vadmin_run (modules/vadmin.c:248): Got: 200
LOGGER: log_request (modules/http.c:300): GET /status
LOGGER: vadmin_run (modules/vadmin.c:246): Running 'status'
LOGGER: vadmin_run (modules/vadmin.c:248): Got: 200
LOGGER: log_request (modules/http.c:300): GET /log/1/BereqURL
LOGGER: log_request (modules/http.c:300): GET /stats
LOGGER: log_request (modules/http.c:300): GET /vcl/arm
LOGGER: vadmin_run (modules/vadmin.c:246): Running 'vcl.show arm'
LOGGER: vadmin_run (modules/vadmin.c:248): Got: 106
LOGGER: log_request (modules/http.c:300): GET /stats
LOGGER: log_request (modules/http.c:300): GET /html/
LOGGER: log_request (modules/http.c:300): GET /html/css/bootstrap.min.css
LOGGER: log_request (modules/http.c:300): GET /html/css/bootstrap-responsive.min.css
LOGGER: log_request (modules/http.c:300): GET /html/css/slider.css
LOGGER: log_request (modules/http.c:300): GET /html/js/jquery-1.10.2.min.js
LOGGER: log_request (modules/http.c:300): GET /html/js/bootstrap.min.js
LOGGER: log_request (modules/http.c:300): GET /html/js/agent.js
LOGGER: log_request (modules/http.c:300): GET /vcljson/
LOGGER: vadmin_run (modules/vadmin.c:246): Running 'vcl.list'
LOGGER: vadmin_run (modules/vadmin.c:248): Got: 200
LOGGER: log_request (modules/http.c:300): GET /log/1/BereqURL
LOGGER: log_request (modules/http.c:300): GET /version
LOGGER: log_request (modules/http.c:300): GET /favicon.ico
LOGGER: log_request (modules/http.c:300): GET /paramjson/
LOGGER: vadmin_run (modules/vadmin.c:246): Running 'param.show -l'
LOGGER: vadmin_run (modules/vadmin.c:248): Got: 200
modules/vparams.c:171: vparams_show_json: Assertion `term' failed. Aborting.
Aborted

Also on the web front I get the following:

Error communicating with agent.
Error listing parameters.
Communication error with agent: 
Varnish-Agent returned 0:

Here's my version:
[root@lamp01 tests]# varnishd -V
varnishd (varnish-4.1.1 revision 66bb824)
Copyright (c) 2006 Verdens Gang AS
Copyright (c) 2006-2015 Varnish Software AS

I compiled the latest varnish-agent from the git repo.

**Comment by aondio** [comment]
Hi,
which branch of the vagent have you used? the branch of the vagent should be the same as the version of varnish, so in this case you should use 4.1

**Comment by rdetwiler** [comment]
Fixed it, was using the wrong branch - Thanks!
