### ISSUE TITLE
memory leaks in vbackends code

### ISSUE THREAD

**Issue by fgsch** [varnish/vagent2#167]
vbackends_show_json() will leak ptr, out1 and out2

**Comment by aondio** [comment]
https://github.com/aondio/vagent2/commit/eba5f45ba89d082f1237f3be404f66d0acc14c3c

I'm not sure if this cover it all, I didn't have time to review it properly(busy with per tons of things to be done at the same time), but hopefully it's a good starting point.

**Comment by fgsch** [comment]
ptr is leaked inside the while loop so it needs to be moved there.

The other 2 are OK.
