### ISSUE TITLE
Inconsistent trailing slash

### ISSUE THREAD

**Issue by marme660** [varnish/vagent2#170]
So for some endpoints training slash matters and not for the other endpoints and I found it confusing when writing tests. It is not a major thing but it would be great if we keep the consistent pattern.

**Comment by gquintard** [comment]
also fixed by the refactoring.

**Comment by freshteapot** [comment]
@gquintard Does that mean it is fixed in master or has it been fixed in a released tag?

I think it means master. As I am running the latest version and it is still not working, but I know a new version is in the pipeline.

Current:
```
varnish-agent 4.1.1
Copyright (c) 2012-2015 Varnish Software Group
```

**Comment by gquintard** [comment]
it's in master, and awaiting release.

**Comment by freshteapot** [comment]
Perfect.

**Comment by freshteapot** [comment]
I can confirm this is on master and the 4.1.2 package that is yet to be released

**Comment by hugocruz** [comment]
released :)
