### ISSUE TITLE
put request to /backend/ endpoint with bad parameter kills the agent

### ISSUE THREAD

**Issue by marme660** [varnish/vagent2#174]
While writing tests, I expected something like Unknown request instead of killing agent. 

curl -X PUT http://localhost:6085/backend -d "healthy" 

varnish-agent[23936]: log_request (modules/http.c:296): 127.0.0.1:3484 - PUT /backend/
varnish-agent[23936]: modules/vbackends.c:171: vbackends_reply: Assertion `arg && *arg' failed. Aborting.

**Comment by gquintard** [comment]
This was fixed some time ago during the refactoring. #drivebyfix

**Comment by freshteapot** [comment]
Agreed. I was just trying to replicate it.
