### ISSUE TITLE
Commands: /vcl/ and /vcljson/ show different names

### ISSUE THREAD

**Issue by L00Cyph3r** [varnish/vagent2#176]
Just installed the lastest agent and found an inconsistency when it comes to the vcl-commands.
When I visit `http://IP/6085/vcl/` I see:

```
available   auto/warm          0 boot
active      auto/warm          9 www_example_com
```

But when I visit `http://IP:6085/vcljson/` I see:

``` JSON
{
    "vcls": [
        {
            "name": "arm",
            "status": "available",
            "refs": "auto/w"
        },
        {
            "name": "arm",
            "status": "active",
            "refs": "auto/w"
        }
    ]
}
```

This makes using the [Varnish Dashboard](https://github.com/brandonwamboldt/varnish-dashboard) quite impossible :(

P.S. I'm using `varnish-5.0.0 revision 99d036f`

**Comment by Dridi** [comment]
There's currently no release of the varnish-agent for Varnish 5.0, does this also happen with 4.1?

Besides VCL labels, I don think there's anything new in the `varnish-cli` output in this area so I'm surprised it breaks.

**Comment by L00Cyph3r** [comment]
Ok, since I had more weird issues with 5.0, I installed `varnish-4.0.2 revision bfe7cd1` from debian repo which made this issue disappear.

However, once I almost wanted to close this ticket, I installed `varnish-4.1.3 revision 5e3b6d2` from the varnish-repo... Guess what...
```
available  auto/warm          7 boot
active     auto/warm          2 7f5fa0e1-d8a5-415c-bf45-543fa9114181
```
```JSON
{
	"vcls": [
		{
			"name": "arm",
			"status": "available",
			"refs": "auto/w"
		},
		{
			"name": "arm",
			"status": "active",
			"refs": "auto/w"
		}
	]
}
```

So uhhh, I'm a bit lost here.

**Comment by Dridi** [comment]
> Ok, since I had more weird issues with 5.0, I installed varnish-4.0.2
revision bfe7cd1 from debian repo which made this issue disappear.
snip...
> So uhhh, I'm a bit lost here.

The 4.1 agent may work with Varnish 5.0 but that's unsupported, and only a
4.0 agent is expected to work with Varnish 4.0.

Please upgrade varnish-agent to the latest 4.1 and try again.

Dridi

**Comment by Dridi** [comment]
Timed out.
