### ISSUE TITLE
Assert error in _assert_VSB_integrity(), ../libvarnish/vsb.c line 91:

### ISSUE THREAD

**Issue by lhwong** [varnish/vagent2#179]
Hi,

I built varnish-agent from master branch on ubuntu.  When executing I got the following error

alchemy@cdn-test1:~/varnish-agent$ sudo varnish-agent
Assert error in _assert_VSB_integrity(), ../libvarnish/vsb.c line 91:
  Condition(s->s_len < s->s_size) not true.
  errno = 2 (No such file or directory)

Same problem when building source code from https://github.com/varnish/vagent2/releases/download/4.1.1/varnish-agent-4.1.1.tar.gz.

I am running varnish-5.0.0 revision 99d036f

Any idea on how to solve the problem?

**Comment by aondio** [comment]
Hi @lhwong,
you are running Varnish 5.0 and trying to use the Varnish-Agent for Varnish 4.1.
Unfortunately the Varnish-Agent for Varnish 5.0 is not available at the moment, you should run Varnish 4.1 with the Varnish-Agent 4.1
