### ISSUE TITLE
Need help in Installing Varnish_Agent on Ubuntu 14.0.4 Server

### ISSUE THREAD

**Issue by prasoonvv** [varnish/vagent2#180]
Hi there,

We are trying to install Varnish Monitoring Extension on an Ubuntu 14.04 server with Varnish version 3.0.7 on it. The installation document says  vagent2 (open source project on GitHub) needs to be installed first and asked us to follow the steps in  https://github.com/varnish /vagent2/blob/master/INSTALL.rst to install vagent2. But the document doesn't contain clear steps to install the Varnish_Agent. Also we did not see any package for Ubuntu 14.04 OS..!! We found the following downloads,

1. varnish-agent_2.2.0_amd64.deb.tar.gz (Debian)
2. varnish-agent-2.2.0-2.x86_64.rpm.tar.gz (RHEL)

Now we have the following questions:

1. Can we use the above packages for Ubuntu 14.0.4 distro and would that be compatible.??
2. What are the prerequisites/minimum requirement for installing Varnish_Agent. We are having Varnish 3.0.7 on our Ubuntu Server.
3. How do we install Varnish Agent on Ubuntu. Could you help us with step by step instructions..??
4. If the current version of Varnish_Agent is not supported on Varnish 3.0.7, how do we get the previous releases which would be compatible..?

Could anyone help us on this. Any suggestions would be much appreciated..!!

Prasoon

**Comment by aondio** [comment]
Hi @prasoonvv,
you are using Varnish 3.0.7(please note that it has reached EOF, consider upgrading). therefore you need to install the branch 3.0 of the vagent.
In which part of the process described here: https://github.com/varnish/vagent2/blob/3.0/INSTALL.rst are you stuck?

Also, where have you found the packages?

**Comment by Dridi** [comment]
ETIMEDOUT
