### ISSUE TITLE
Support https requests

### ISSUE THREAD

**Issue by freshteapot** [varnish/vagent2#186]
# What
Make the agent via flag(s) only accept https requests. Start the http daemon with builtin https support based on key / pem file.

A nice extra would be, requests coming in via http to be redirected to https version.

A quick look at an [example](https://github.com/rboulton/libmicrohttpd/blob/master/src/examples/https_fileserver_example.c#L179) of how to do ssl in libmicrohttpd.

# Reference
- [line in http_run where the daemon is started](https://github.com/varnish/vagent2/blob/master/src/modules/http.c#L457)
- [example of setting up ssl with libmicrohttpd](https://github.com/rboulton/libmicrohttpd/blob/master/src/examples/https_fileserver_example.c)

**Comment by gquintard** [comment]
Closing this as the repository is going to be retired soon, and we won't develop new features for it.
