### ISSUE TITLE
Make agent varnish-5.1.1 compatible

### ISSUE THREAD

**Issue by ghenzler** [varnish/vagent2#187]
When running latest agent v4.1.2 with varnish 5.1.1 (released last week)  I get 

```
Error communicating with agent.
Couldn't get stats: 
```

when calling dashboard at `/html/`

**Comment by Dridi** [comment]
There are no plans for vagent2 against Varnish 5.1 currently, sorry.

**Comment by ghenzler** [comment]
@Dridi what would you suggest as varnish agent alternative then?

**Comment by Dridi** [comment]
I'm not aware of any non-commercial alternative. We currently don't have bandwidth to get the agent working with 5.x releases, especially if we want to take advantage of new features like VCL labels. We would however welcome and review contributions in that direction.

**Comment by vladbondarenko** [comment]
+1, also need vagent2 for varnish 5.1
