### ISSUE TITLE
Problems with Chrome? LogIn failed

### ISSUE THREAD

**Issue by t-zimmermann** [varnish/vagent2#190]
When I try to login on:
http://localhost:6085/home/
with Google Chrome
I only get the white page: failed

not working: 
Chromium: Version 53.0.2785.143 Built on Ubuntu , running on LinuxMint 17.3 (64-bit)
Chrome: Version 57.0.2987.133 (64-bit)
working: 
Firefox: 52.0.2 (64-Bit)
Opera: 44.0.2510.857

**Comment by Dridi** [comment]
There's no `/home` endpoint available, did you mean `/html` instead?

See http://localhost:6085/ for supported URLs.
