### ISSUE TITLE
Assertion when parse_name fails to get an incomplete parameter

### ISSUE THREAD

**Issue by hugocruz** [varnish/vagent2#195]
Currently varnish-agent asserts when somehow the parameters don't have a new line
```c
static const char *
parse_name(const char *raw, struct param_opt *p)
{
	const char *eol;

	assert(raw != NULL);
	assert(p != NULL);

	assert(skip_space((char *)raw) == raw);
	eol = strchr(raw, '\n');
	assert(eol != NULL);

	assert(p->name == NULL);
	p->name = strndup(raw, eol - raw);
	assert(p->name != NULL);

	return (eol);
}
```

https://github.com/varnish/vagent2/blob/8d2ea9791e6d5a5e032443984354cf34f90595ab/src/modules/vparams.c#L147

A more elegant way of handling this, besides an assert is ideal.

**Comment by gquintard** [comment]
This repository is going to be retired soon, meaning no more development. We will however consider PRs fixing bugs, and I'm inclined to treat this as such, if someone want to work on it.
