### ISSUE TITLE
Running "/paramjson" results in Assertion fail

### ISSUE THREAD

**Issue by Littlericket** [varnish/vagent2#196]
After running GET "/paramjson" on a varnish 4 server, the agent aborts with

`LOGGER: vadmin_run (modules/vadmin.c:268): Running 'param.show -l'
LOGGER: vadmin_run (modules/vadmin.c:270): Got: 200
modules/vparams.c:291: fill_entry: Assertion 'p->def == NULL' failed. Aborting.
Aborted
`

`varnish-agent 4.1.3
Copyright (c) 2012-2016 Varnish Software Group
`

`varnishd (varnish-4.0.5 revision 07eff4c29)
Copyright (c) 2006 Verdens Gang AS
Copyright (c) 2006-2014 Varnish Software AS
`

**Comment by hugocruz** [comment]
Hello, I believe you have a miss match between agent and Varnish versions. 

Varnish Agent 4.0.x is for Varnish 4.0 series
Varnish Agent 4.1.x is for Varnish 4.1 series

**Comment by Littlericket** [comment]
Hello, youre right.
I didnt found any documentation on that yet. 

But it works fine now.

**Comment by hugocruz** [comment]
I will add that to the README.
