### ISSUE TITLE
VCL uploads over 2MB fail

### ISSUE THREAD

**Issue by rezan** [varnish/vagent2#203]
Looks like this is due to:

https://github.com/varnish/vagent2/blob/8fa52e146cf6b3ad0450225472569ce36f271be3/src/modules/http.c#L48

**Comment by rezan** [comment]
I have a potential fix here:

https://github.com/varnish/vagent2/commit/2223dc45aa165b16ebdac2cee4263888edda3044

Needs some kind of review. I tested a large VCL and it worked.

**Comment by Dridi** [comment]
A better solution would be to use a VSB to accumulate body chunks, with `VSB_bcat`. This way there's no fiddling with a character and we keep the original body pristine, hide memory management under the rug, kill the arbitrary limit, and cut out a lot of code.

Regarding the limit for uploads, I understand what risk it mitigates. However the agent is meant to be run internally and not publicly exposed through the web. So unless we have a tunable, I'm all for killing the arbitrary limit and check that unauthenticated requests get rejected before we grab the body.

Thoughts?

**Comment by gquintard** [comment]
stupid question, but shouldn't we trust anyone with the proper credentials
and close the connection on the others?
-- 
Guillaume Quintard

**Comment by Dridi** [comment]
That should already be the case, I'm suggesting we verify that "should" is really "is".

**Comment by gquintard** [comment]
cool, then the body size isn't really an issue

-- 
Guillaume Quintard

**Comment by rezan** [comment]
@Dridi, the problem is that we allocate and write to the upload buffer *before* we authorize. So the agent will potentially buffer a 6MB upload and then find out the user is not authorize and then fail. At least in my testing, that is what is happening.

**Comment by Dridi** [comment]
The VSB doesn't change anything, it merely simplifies memory handling. If we are buffering the request body before checking the authentication, then we should fix that first.

**Comment by rezan** [comment]
> If we are buffering the request body before checking the authentication, then we should fix that first.

@Dridi Are you volunteering yourself for this effort?

**Comment by Dridi** [comment]
That is correct :)
