### ISSUE TITLE
No issue here ... just saying thanks!

### ISSUE THREAD

**Issue by cube-dan** [varnish/vagent2#210]
I wanted to take a moment to say thanks for releasing Varnish Agent 2 into the wild. I installed it today following [this tutorial](https://ma.ttias.be/varnish-agent-html-frontend-manage-monitor-varnish-installation/) and it just worked!

I'm still digging into everything that Varnish Agent 2 (and varnish cache in general) have to offer but I'm 100% sure that your efforts have made the task of diving into varnish much, much, easier; for that I'm grateful.

Keep up the great work guys!

**Comment by gquintard** [comment]
hi @cube-dan, thanks!
