### ISSUE TITLE
html/agent.js: request rate is bogus when the agent is slow or temporarily down

### ISSUE THREAD

**Issue by KristianLyng** [varnish/vagent2#26]
Since agent.stats contains 4 samples of stats, we got some history. If everything updates every second, that's fine. Unfortunately we do not look at time stamps for showing req/s, so if we turn off the agent and bring it back up again 10 seconds later, we'll get a req/s calculated from the values of 10 extra seconds.

**Comment by gquintard** [comment]
This repository is going to be retired soon, meaning no more development. We will however consider PRs fixing bugs, if someone want to work on it.
