### ISSUE TITLE
vlog: Add filter support somehow

### ISSUE THREAD

**Issue by KristianLyng** [varnish/vagent2#33]
Yves suggested we match the URL-syntax with what vstatd....vsc does.

Can someone provide example urls?

I would really really really like it if we could keep all varnishlog requests as GET requests.

**Comment by hugocruz** [comment]
Taking the most out of Varnish VSL would be something interesting as a feature.  That raises a lot of other issues. Just my two cents

**Comment by Dridi** [comment]
ETIMEDOUT
