### ISSUE TITLE
Parameters and spaces (e.g: cc_command)

### ISSUE THREAD

**Issue by KristianLyng** [varnish/vagent2#55]
Setting cc_command in the frontend is currently broken.

It's arguable that this is a bug in the backend...

This is where the VSB_Quote logic that I've commented out comes into play I suppose.

Not decided on how to fix this. If the frontend just throws "" around it, it'll work, but is that enough? .... need time to think (or get comments)

**Comment by gquintard** [comment]
This repository is going to be retired soon, meaning no more development. We will however consider PRs fixing bugs, and I'm inclined to treat this as such, if someone want to work on it.
