### ISSUE TITLE
HTTP Binding to other IP addresses than 0.0.0.0

### ISSUE THREAD

**Issue by KristianLyng** [varnish/vagent2#6]
microhttpd supports it, just not my old version.

**Comment by callesoe** [comment]
Me too!

**Comment by luckyraul** [comment]
+1 for ability to choose listen ip

**Comment by denisbr** [comment]
This has been a requested feature from various parties, especially handy for easier setup on multi-homed servers.

**Comment by markslater** [comment]
+1!

**Comment by webbrandon** [comment]
It's supported : 
```bash
varnish-agent \
      -d \
      -T 0.0.0.0:6082 \
      -z 0.0.0.0:6085 \
      -H /var/www/html/varnish-dashboard
```

**Comment by Dridi** [comment]
@webbrandon not really, the -z option refers to the [VAC](https://www.varnish-software.com/plus/varnish-administration-console/), a tool the agent may connect to to register itself in a cluster context. If you use the -z option this way, your `varnish-agent` process will try to connect to itself.

This is not a priority, but patches are welcome.

**Comment by Dridi** [comment]
FYI, SomeOne:tm: decided to send patches and I'm reviewing them ;-)

See #201.
