### ISSUE TITLE
debian: Package upgrade doesn't seem to start the agent back up

### ISSUE THREAD

**Issue by KristianLyng** [varnish/vagent2#60]
On upgrading the debian package the agent is left stopped at the moment. Not a big deal, but it seems wrong.

**Comment by Dridi** [comment]
@mariusmagureanu can you please check whether this is still relevant?

**Comment by mariusmagureanu** [comment]
Yes, still seems to be the case here.

I've just installed and started 4.1.2 on Stretch, after upgrading to 4.1.3 I had to start the agent manually.

**Comment by Dridi** [comment]
@stone halp?

**Comment by gquintard** [comment]
This repository is going to be retired soon, meaning no more development. We will however consider PRs fixing bugs, if someone want to work on it.
