### ISSUE TITLE
Wrong libvarnishapi path 

### ISSUE THREAD

**Issue by akuznecov** [varnish/vagent2#80]
Hello,

I got issue with launching Agent with Varnish installed to custom path:

`# /opt/vagent2/agent2/bin/varnish-agent -H /opt/vagent2/dashboard/ -T 127.0.0.1:9082 -K /opt/vagent2/agent2/secret`

> /opt/vagent2/agent2/bin/varnish-agent: /usr/lib64/libvarnishapi.so.1: no version information available (required by /opt/vagent2/agent2/bin/varnish-agent)
> /opt/vagent2/agent2/bin/varnish-agent: relocation error: /opt/vagent2/agent2/bin/varnish-agent: symbol VSM_New, version LIBVARNISHAPI_1.0 not defined in file libvarnishapi.so.1 with link time reference

agent2 installed with next params:
`# PKG_CONFIG_PATH=/opt/varnish3/lib/pkgconfig ./configure --prefix=/opt/vagent2/agent2`

ldd outputs:
`# ldd /opt/vagent2/agent2/bin/varnish-agent`

```
/opt/vagent2/agent2/bin/varnish-agent: /usr/lib64/libvarnishapi.so.1: no version information available (required by /opt/vagent2/agent2/bin/varnish-agent)
    linux-vdso.so.1 =>  (0x00007fff657ff000)
    libvarnishapi.so.1 => /usr/lib64/libvarnishapi.so.1 (0x00007febf6bb0000)
    libmicrohttpd.so.10 => /usr/lib64/libmicrohttpd.so.10 (0x00007febf699d000)
    libpthread.so.0 => /lib64/libpthread.so.0 (0x00007febf677f000)
    libnsl.so.1 => /lib64/libnsl.so.1 (0x00007febf6566000)
    libcurl.so.4 => /usr/lib64/libcurl.so.4 (0x00007febf6313000)
    libc.so.6 => /lib64/libc.so.6 (0x00007febf5f7f000)
    libpcre.so.0 => /lib64/libpcre.so.0 (0x00007febf5d53000)
    libgnutls.so.26 => /usr/lib64/libgnutls.so.26 (0x00007febf5ab0000)
    libgcrypt.so.11 => /lib64/libgcrypt.so.11 (0x00007febf583a000)
    libdl.so.2 => /lib64/libdl.so.2 (0x00007febf5636000)
    libgpg-error.so.0 => /lib64/libgpg-error.so.0 (0x00007febf5432000)
    librt.so.1 => /lib64/librt.so.1 (0x00007febf5229000)
    /lib64/ld-linux-x86-64.so.2 (0x00007febf6dc5000)
    libidn.so.11 => /lib64/libidn.so.11 (0x00007febf4ff7000)
    libldap-2.4.so.2 => /lib64/libldap-2.4.so.2 (0x00007febf4daa000)
    libgssapi_krb5.so.2 => /lib64/libgssapi_krb5.so.2 (0x00007febf4b65000)
    libkrb5.so.3 => /lib64/libkrb5.so.3 (0x00007febf487f000)
    libk5crypto.so.3 => /lib64/libk5crypto.so.3 (0x00007febf4653000)
    libcom_err.so.2 => /lib64/libcom_err.so.2 (0x00007febf444e000)
    libz.so.1 => /lib64/libz.so.1 (0x00007febf4238000)
    libssl3.so => /usr/lib64/libssl3.so (0x00007febf4002000)
    libsmime3.so => /usr/lib64/libsmime3.so (0x00007febf3dd5000)
    libnss3.so => /usr/lib64/libnss3.so (0x00007febf3a9a000)
    libnssutil3.so => /usr/lib64/libnssutil3.so (0x00007febf386f000)
    libplds4.so => /lib64/libplds4.so (0x00007febf366a000)
    libplc4.so => /lib64/libplc4.so (0x00007febf3465000)
    libnspr4.so => /lib64/libnspr4.so (0x00007febf3228000)
    libssh2.so.1 => /usr/lib64/libssh2.so.1 (0x00007febf2fff000)
    libtasn1.so.3 => /usr/lib64/libtasn1.so.3 (0x00007febf2def000)
    liblber-2.4.so.2 => /lib64/liblber-2.4.so.2 (0x00007febf2bdf000)
    libresolv.so.2 => /lib64/libresolv.so.2 (0x00007febf29c5000)
    libsasl2.so.2 => /usr/lib64/libsasl2.so.2 (0x00007febf27ab000)
    libkrb5support.so.0 => /lib64/libkrb5support.so.0 (0x00007febf259f000)
    libkeyutils.so.1 => /lib64/libkeyutils.so.1 (0x00007febf239c000)
    libssl.so.10 => /usr/lib64/libssl.so.10 (0x00007febf213e000)
    libcrypto.so.10 => /usr/lib64/libcrypto.so.10 (0x00007febf1da4000)
    libcrypt.so.1 => /lib64/libcrypt.so.1 (0x00007febf1b6d000)
    libselinux.so.1 => /lib64/libselinux.so.1 (0x00007febf194d000)
    libfreebl3.so => /lib64/libfreebl3.so (0x00007febf16eb000)
```

`# ldd /opt/varnish3/bin/varnishadm`

```
    linux-vdso.so.1 =>  (0x00007fff92131000)
    libvarnishapi.so.1 => /opt/varnish3/lib/libvarnishapi.so.1 (0x00007f0b7d2fc000)
    libvarnishcompat.so => /opt/varnish3/lib/varnish/libvarnishcompat.so (0x00007f0b7d0fa000)
    libnsl.so.1 => /lib64/libnsl.so.1 (0x00007f0b7ced3000)
    libm.so.6 => /lib64/libm.so.6 (0x00007f0b7cc4f000)
    libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f0b7ca31000)
    libc.so.6 => /lib64/libc.so.6 (0x00007f0b7c69e000)
    libpcre.so.0 => /lib64/libpcre.so.0 (0x00007f0b7c472000)
    /lib64/ld-linux-x86-64.so.2 (0x00007f0b7d50f000)
```

`ldconfig -n /opt/varnish3/lib` doesn't help

What is wrong here?

p.s. if i remove varnish libs from /usr/lib64, then i got:

> /opt/vagent2/agent2/bin/varnish-agent: error while loading shared libraries: libvarnishapi.so.1: cannot open shared object file: No such file or directory

p.s.s. I have two varnish installations on this system
1. varnish2 - binary, installed from reposiroty
2. varnish3 - build from sources and installed to /opt/varnish3

**Comment by intelbg** [comment]
I have the same problem. Can anyone help with this? I tryed as the person above said with compiled varnish and varnish installed from rpm in /usr/local/varnish/, also with ldconfig and the following exports command before compiling, but no effect:

 export VARNISHAPI_CFLAGS=-I/usr/local/varnish/include
 export VARNISHAPI_LIBS="-L/usr/local/varnish/lib -lvarnishapi"

The error is the following:

ipc.c:62:18: error: vcli.h: No such file or directory
cc1: warnings being treated as errors
ipc.c: In function ‘ipc_send’:
ipc.c:103: error: implicit declaration of function ‘VCLI_ReadResult’
ipc.c:103: error: nested extern declaration of ‘VCLI_ReadResult’
ipc.c: In function ‘ipc_cmd’:
ipc.c:183: error: implicit declaration of function ‘VCLI_WriteResult’
ipc.c:183: error: nested extern declaration of ‘VCLI_WriteResult’
make[2]: *** [varnish_agent-ipc.o] Error 1
make[2]: Leaving directory `/root/vagent2-master/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/root/vagent2-master'
make: *** [all] Error 2

**Comment by fgsch** [comment]
Your problem is different:

```
ipc.c:62:18: error: vcli.h: No such file or directory
```

Most likely your CFLAGS include path is incorrect.

**Comment by intelbg** [comment]
It's the correct path as I typed I execute the following command and the path is there:

export VARNISHAPI_CFLAGS=-I/usr/local/varnish/include

is it must varnish to be compiled first?

**Comment by fgsch** [comment]
@intelbg 
Please provide step by step of what you are doing, including Varnish version and vagent2 branch.

**Comment by intelbg** [comment]
Thank you about your reply, here are emy steps as the version of varnish is 3.0.7 and branch of vagent2 is 3.0.

yum install -y libedit-devel libtool libedit-devel pcre-devel pkgconfig jemalloc-devel
git clone -b 3.0 https://github.com/varnish/vagent2.git
cd vagent2/
export VARNISHAPI_CFLAGS=-I/usr/local/varnish/include
export VARNISHAPI_LIBS="-L/usr/local/varnish/lib -lvarnishapi"
./autogen.sh 
 ./configure --prefix=/usr/local/varnish
/varnish-agent
 make

root@varnish3 [~/vagent2]# ll /usr/local/varnish/include/varnish/
total 56
drwxr-xr-x 2 root root 4096 Aug  6 19:06 ./
drwxr-xr-x 3 root root 4096 Aug  6 19:06 ../
-rw-r--r-- 1 root root 7567 Aug  6 19:06 varnishapi.h
-rw-r--r-- 1 root root 5992 Aug  6 19:06 vcli.h
-rw-r--r-- 1 root root 2053 Aug  6 19:06 vsc_all.h
-rw-r--r-- 1 root root 9953 Aug  6 19:06 vsc_fields.h
-rw-r--r-- 1 root root 1820 Aug  6 19:06 vsc.h
-rw-r--r-- 1 root root 2720 Aug  6 19:06 vsl.h
-rw-r--r-- 1 root root 2639 Aug  6 19:06 vsl_tags.h
-rw-r--r-- 1 root root 3093 Aug  6 19:06 vsm.h

**Comment by Dridi** [comment]
Please move to varnish 4.1 to get a supported setup.

ETIMEDOUT
