### ISSUE TITLE
GET /backendjson/ should return a list of backend, its state indicator and state

### ISSUE THREAD

**Issue by yveshwang** [varnish/vagent2#84]
for example

b0 Still healthy 4--X-S-RH 9 8 10 0.029291 0.030875 HTTP/1.1 200 Ok

can be presented in json with the appropriate key representing the above information.

**Comment by KristianLyng** [comment]
debug.health is kinda unwanted. This should be handled either through logs or when varnish cli adds support for this. But I agree in principle.

**Comment by aondio** [comment]
Closing this since there is a new module that does that: commit t 7c1fb3a
