### ISSUE TITLE
/vac_register, not sure what this does but it certainly doesnt do what it said it should

### ISSUE THREAD

**Issue by yveshwang** [varnish/vagent2#99]
LOGGER: send_curl (modules/vac_register.c:75): Not registering with the VAC. Unknown vac url. Try using -z

**Comment by andjimrio** [comment]
The same in my case:

```bash
sh-4.2# varnish-agent -d -H /var/www/html/varnish-dashboard
n_arg_sock (modules/vadmin.c:144): -T argument computed to: ::1 6082
main (main.c:355): Plugins initialized. -d argument given, so not forking.
LOGGER: send_curl (modules/vac_register.c:77): Not registering with the VAC. Unknown vac url. Try using -z
LOGGER: http_run (modules/http.c:456): HTTP starting on port 6085
LOGGER: vac_register (modules/vac_register.c:127): Couldn't register with the VAC
```

I am trying to deploy in a OpenShift Pod and the Agents cannot capture any traffic. In despite of, in local with docker-compose works without problem. Should I add by -z the IP of the server or anything?

**Comment by mariusmagureanu** [comment]
The ``-z`` option is used for registering an agent instance against the VAC, but this option has nothing to do with the actual connection between varnish and the agent.

What is the actual problem? Has the agent not managed to connect to varnish? 
If so, what varnish version are you running on?

Did you by any chance altered varnish's ``-T`` and/or ``-n`` options? If so, then the agent should be made aware of these changes.

**Comment by andjimrio** [comment]
Hi and thank you!

My varnish execution is: 
```bash
varnishd -F -f /etc/varnish/default.vcl -a 0.0.0.0:80 -T localhost:6082 -s malloc,256m
```

It is correct according to docs, isn't? In spite of, works without problem in local, but not in server.
